In [1]:
#1
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)

print("数组维度(ndim):", arr.ndim)
print("数组形状(shape):", arr.shape)
print("元素总个数(size):", arr.size)

数组维度(ndim): 2
数组形状(shape): (3, 4)
元素总个数(size): 12


In [2]:
#2
import numpy as np

# 创建浮点数组
arr_float = np.array([1.5, 2.6, 3.7, 4.8])
print("转换前数组:", arr_float)
print("转换前数据类型:", arr_float.dtype.name)

# 转换为32位整数
arr_int = arr_float.astype(np.int32)
print("\n转换后数组:", arr_int)
print("转换后数据类型:", arr_int.dtype.name)

转换前数组: [1.5 2.6 3.7 4.8]
转换前数据类型: float64

转换后数组: [1 2 3 4]
转换后数据类型: int32


In [3]:
#3
import numpy as np

# 创建二维数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 切片：前两行，第2到第3列（索引从0开始，列1到3不包含3）
sub_arr = arr[:2, 1:3]
print("切片结果:\n", sub_arr)

切片结果:
 [[2 3]
 [6 7]]


In [4]:
#4
import numpy as np

# 给定数组
arr = np.array([10, 15, 20, 25, 30, 35])

# 1. 花式索引提取第1、3、5个元素（索引0,2,4）
fancy_index = arr[[0, 2, 4]]
print("花式索引结果:", fancy_index)

# 2. 布尔索引提取所有大于20的元素
bool_index = arr[arr > 20]
print("布尔索引结果:", bool_index)

花式索引结果: [10 20 30]
布尔索引结果: [25 30 35]


In [5]:
#5
import numpy as np

# 创建全0数组和一维数组
arr_a = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])

# 利用广播机制相加
result = arr_a + arr_b
print("广播相加结果:\n", result)

广播相加结果:
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [6]:
#6
import numpy as np

# 给定数组
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

# 1. 计算x中每个元素的平方根
sqrt_x = np.sqrt(x)
print("x的平方根数组:", sqrt_x)

# 2. 找出对应位置上的最大值
max_result = np.maximum(sqrt_x, y)
print("对应位置最大值数组:", max_result)

x的平方根数组: [1. 2. 3. 4.]
对应位置最大值数组: [2. 2. 4. 5.]


In [7]:
#7
import numpy as np

# 创建三维数组
arr = np.arange(24).reshape((2, 3, 4))

# 转置轴顺序为(1, 0, 2)
transposed_arr = arr.transpose((1, 0, 2))
print("转置后数组的形状:", transposed_arr.shape)

转置后数组的形状: (3, 2, 4)


In [8]:
#8
import numpy as np

# 给定数组
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

# 使用np.where进行条件选择
result = np.where(arr_con, arr_x, arr_y)
print("条件选择结果:", result)

条件选择结果: [1 6 7]


In [9]:
#9
import numpy as np

# 创建二维数组
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])

# 1. 计算所有元素的算术平均值
mean_value = arr.mean()
print("所有元素的平均值:", mean_value)

# 2. 沿axis=0方向（按列）从小到大排序
sorted_arr = np.sort(arr, axis=0)
print("按列排序后的数组:\n", sorted_arr)

所有元素的平均值: 3.888888888888889
按列排序后的数组:
 [[3 2 2]
 [4 3 2]
 [6 6 7]]


In [10]:
#10
import numpy as np

# 1. 设置随机数种子
np.random.seed(10)

# 2. 生成两个(2,2)的均匀分布随机矩阵
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
print("矩阵A:\n", A)
print("\n矩阵B:\n", B)

# 3. 计算矩阵点积
dot_product = np.dot(A, B)
print("\n矩阵A和B的点积:\n", dot_product)

矩阵A:
 [[0.77132064 0.02075195]
 [0.63364823 0.74880388]]

矩阵B:
 [[0.49850701 0.22479665]
 [0.19806286 0.76053071]]

矩阵A和B的点积:
 [[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
